/*
 * Copyright (c) 2008 CO-CONV, Corp. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _UIPC_SYSCALLS_H_
#define _UIPC_SYSCALLS_H_

NTSTATUS SCTPCreateSocket(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchOpenRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchBindRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchConnectRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchListenRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchAcceptRequest(IN PIRP, IN PIO_STACK_LOCATION);
#ifdef SCTP
NTSTATUS SCTPDispatchPeeloffRequest(IN PIRP, IN PIO_STACK_LOCATION);
#endif
NTSTATUS SCTPDispatchSendRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchSendRequestDeferred(IN PIRP, IN PIO_STACK_LOCATION);
void SCTPDispatchSendRequestCanceled(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchSendMsgRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchSendMsgRequestDeferred(IN PIRP, IN PIO_STACK_LOCATION);
void SCTPDispatchSendMsgRequestCanceled(IN PIRP, IN PIO_STACK_LOCATION);
#ifdef SCTP
NTSTATUS SCTPDispatchSctpSendRequest(IN PIRP, IN PIO_STACK_LOCATION);
#endif
NTSTATUS SCTPDispatchRecvRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchRecvRequestDeferred(IN PIRP, IN PIO_STACK_LOCATION);
void SCTPDispatchRecvRequestCanceled(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchRecvMsgRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchRecvMsgRequestDeferred(IN PIRP, IN PIO_STACK_LOCATION);
void SCTPDispatchRecvMsgRequestCanceled(IN PIRP, IN PIO_STACK_LOCATION);
#ifdef SCTP
NTSTATUS SCTPDispatchSctpRecvRequest(IN PIRP, IN PIO_STACK_LOCATION);
#endif
NTSTATUS SCTPDispatchSelectRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchEventSelectRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchEnumNetworkEventsRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchSetOptionRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchGetOptionRequest(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchGetSockName(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchGetPeerName(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchShutdown(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchIoctl(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPCloseSocket(IN PIRP, IN PIO_STACK_LOCATION);

NTSTATUS SCTPCreateTdi(IN PIRP, IN PIO_STACK_LOCATION, IN int, IN int);
NTSTATUS SCTPDispatchTdiAssociateAddress(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiDisassociateAddress(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiConnect(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiConnectComplete(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiDisconnect(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiSend(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiSendDatagram(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiReceive(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiReceiveDatagram(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiSetEventHandler(IN PIRP, IN PIO_STACK_LOCATION);
NTSTATUS SCTPDispatchTdiQueryInformation(IN PSCTP_SOCKET, IN PSCTP_DGRCV_REQUEST);
NTSTATUS SCTPCloseTdi(IN PIRP, IN PIO_STACK_LOCATION);

#endif /* _UIPC_SYSCALLS_H_ */
